server 
{
    listen       80;
    server_name  localhost;

    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
    add_header 'Access-Control-Allow-Private-Network' 'true';

    location / 
        {
            # root   /usr/share/nginx/html;
            # index  index.html index.htm;
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            # try_files $uri $uri/ /index.html;
            try_files $uri.html $uri $uri/ /index.html;
        }

        location /mpesa
        {
            proxy_pass http://172.14.0.160:8000/api;
        }


        location /shortcode
        {
            proxy_pass http://172.14.0.136:8082/shortcodes/api;
        }

}


# chrome://flags/#block-insecure-private-network-requests